fieldmappings:
  CallTrace: calltrace
  Channel: event_channel
  Source: hawk_source
  source: hawk_source
  CommandLine: command
  DNSAddress: dns_address
  DestinationIp: ip_dst
  DestinationPort: ip_dport
  EventID: vendor_id
  IPAddress: ip_src
  ImageLoaded: image_loaded
  IpAddress: ip_src
  MD5: file_hash_md5
  ParentImage: parent_image
  ParentCommandLine: parent_command
  parentcommandline: parent_command
  ParentCommand: parent_command
  parentcommand: parent_command
  ProcessName: image
  ImagePath: image
  imagepath: image
  QueryName: dns_query
  queryname: dns_query
  c-uri-extension: c-uri-extension
  c_uri_extension: c-uri-extension
  properties.message: properties.message
  properties_message: properties.message
  ScriptBlockText: value
  scriptblocktext: value
  DestinationHostname: ip_dst_host
  destinationhostname: ip_dst_host
  SourceImage: parent_image
  sourceimage: parent_image
  TargetImage: target_image
  targetimage: target_image
  EventName: event_name
  eventname: event_name
  EventSource: event_source
  eventsource: event_source
  PipeName: pipe_name
  pipename: pipe_name
  ServiceName: service_name
  servicename: service_name
  ServiceFileName: filename
  servicefilename: filename
  RemoteName: remote_name
  remotename: remote_name
  GrantedAccess: access_mask
  grantedaccess: access_mask
  AccessMask: access_mask
  accessmask: access_mask
  IntegrityLevel: integrity_level
  integritylevel: integrity_level
  OperationName: operation_name
  operationname: operation_name
  SearchFilter: search_filter
  searchfilter: search_filter
  ContextInfo: context_info
  contextinfo: context_info
  OpNum: op_num
  opnum: op_num
  SHA1: file_hash_sha1
  SHA: file_hash_sha1
  sha: file_hash_sha1
  SHA256: file_hash_sha256
  SHA512: file_hash_sha512
  sha512: file_hash_sha512
  OriginalFileName: filename
  originalfilename: filename
  Hashes: hashes
  hashes: hashes
  Signed: signature
  Status: value
  TargetFilename: filename
  TargetObject: object_target
  Description: image_description
  description: image_description
  User: correlation_username
  cs-host: http_host
  c-host: http_host
  c-useragent: http_user_agent
  cs-useragent: http_user_agent
  cs-user-agent: http_user_agent
  cs-uri-query: http_query
  c-uri-query: http_query
  cs-method: http_method
  sc-status: http_status_code
  dst:
    - ip_dst_host
  dst_ip:
    - ip_dst
  host: ip_src
  hostname: ip_src_host
  query: dns_query
  src:
    - ip_src_host
  src_ip:
    - ip_src
